services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
            - postgres-data:/var/lib/postgresql/data
    networks:
      - eyelab-net

  app:
    build: 
        context: .
        dockerfile: Dockerfile-light
    container_name: catascan-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - eye-images:/app/uploads
      - admin-logs:/app/logs
    depends_on:
      - postgres_db
    networks:
      - eyelab-net

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    depends_on:
      - app
    networks:
      - eyelab-net

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - eyelab-net

networks:
  eyelab-net:

volumes:
  postgres-data:
  eye-images:
  admin-logs:
