# -----------------------------
# Test profile
# In-memory H2 database
# -----------------------------
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: h2
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2