# -----------------------------
# Development profile
# -----------------------------
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
      cataract: DEBUG