apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'catascan-api'
        metrics_path: '/management/prometheus'
        static_configs:
          - targets: ['catascan-api-service.default.svc.cluster.local:8080']

