apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2    # or whatever storage class you’re using in AWS
  resources:
    requests:
      storage: 20Gi

